/**
 * Catálogo oficial de preços TOA com reajuste definitivo de repasse (+0,74128%).
 * Valor base calibrado × fator 1,0074128 (arredondado a 2 decimais).
 * Atividades nunca pagas no gabarito ficam em 0. Editáveis no modal.
 */
export type AtividadeToaCatalogo = {
  tipo: string;
  tipoAtividade: string;
  valor: number;
};

export const ATIVIDADES_TOA_CATALOGO: AtividadeToaCatalogo[] = [
  { tipo: "ADESÃO", tipoAtividade: "1 - ADESAO - INSTALACAO DE ASSINATURA", valor: 214.71 },
  { tipo: "RETIRADA DE PONTO", tipoAtividade: "4 - RETIRAR PONTO", valor: 25.9 },
  { tipo: "RETIRADA DE EQUIPAMENTO", tipoAtividade: "5 - RETIRAR EQUIPAMENTO", valor: 0 },
  { tipo: "MUDANÇA DE ENDEREÇO", tipoAtividade: "12 - MUDANCA DE ENDERECO - INSTALAR ASSINATURA", valor: 185.53 },
  { tipo: "SERVIÇOS", tipoAtividade: "15 - MUDANCA DE LOCAL DE PONTO", valor: 168.31 },
  { tipo: "MUDANÇA DE PACOTE", tipoAtividade: "24 - MUDANCA DE PACOTE", valor: 94.33 },
  { tipo: "SERVIÇOS", tipoAtividade: "31 - REFAZER INSTALACAO", valor: 220.1 },
  { tipo: "DESCONEXÃO", tipoAtividade: "32 - DESCONEXAO I C/ RETIRADA DE EQUIPAMENTO", valor: 0 },
  { tipo: "SERVIÇOS", tipoAtividade: "33 - REINSTALACAO - ASSINATURA", valor: 116.53 },
  { tipo: "ADESÃO", tipoAtividade: "43 - ADESAO - INSTALAR PONTO VIRTUA", valor: 213.25 },
  { tipo: "SERVIÇOS", tipoAtividade: "44 - INSTALAR PONTO VIRTUA", valor: 176.86 },
  { tipo: "MUDANÇA DE ENDEREÇO", tipoAtividade: "45 - MUDANCA DE ENDERECO - INSTALAR PONTO ADICIONAL VIRTUA", valor: 0 },
  { tipo: "SERVIÇOS", tipoAtividade: "46 - REINSTALACAO - PONTO ADICIONAL VIRTUA", valor: 77.68 },
  { tipo: "VISITA TÉCNICA", tipoAtividade: "48 - VISITA TECNICA - VIRTUA", valor: 0 },
  { tipo: "VISITA TÉCNICA", tipoAtividade: "50 - VISITA TECNICA - VOIP", valor: 0 },
  { tipo: "ADESÃO", tipoAtividade: "51 - ADESAO - INSTALACAO DE ASSINATURA DIGITAL", valor: 259.71 },
  { tipo: "ADESÃO", tipoAtividade: "52 - ADESAO - INSTALAR SERVICO CONEXAO ADICIONAL DIGITAL", valor: 66.93 },
  { tipo: "SERVIÇOS", tipoAtividade: "53 - INSTALAR SERVICO CONEXAO ADICIONAL DIGITAL", valor: 147.25 },
  { tipo: "MUDANÇA DE ENDEREÇO", tipoAtividade: "54 - MUDANCA DE ENDERECO - INSTALAR ASSINATURA DIGITAL", valor: 207.3 },
  { tipo: "MUDANÇA DE ENDEREÇO", tipoAtividade: "55 - MUDANCA ENDERECO - INSTALAR SERVICO CONEXAO ADIC DIG", valor: 64.74 },
  { tipo: "SERVIÇOS", tipoAtividade: "56 - MUDANCA DE LOCAL DE PONTO DIGITAL", valor: 168.31 },
  { tipo: "MUDANÇA DE PACOTE", tipoAtividade: "57 - MUDANCA DE PACOTE DIGITAL", valor: 99.54 },
  { tipo: "SERVIÇOS", tipoAtividade: "59 - REINSTALACAO - ASSINATURA DIGITAL", valor: 116.53 },
  { tipo: "VISITA TÉCNICA", tipoAtividade: "62 - VISITA TECNICA DIGITAL", valor: 0 },
  { tipo: "RETORNO", tipoAtividade: "69 - RETORNO DE CREDENCIADA", valor: 0 },
  { tipo: "DESCONEXÃO", tipoAtividade: "79 - DESCONEXAO OPCAO C/ RETIRADA DE EQUIPAMENTO", valor: 0 },
  { tipo: "SERVIÇOS", tipoAtividade: "83 - INSTALAR PONTO VOIP", valor: 124.01 },
  { tipo: "RETIRADA DE EQUIPAMENTO", tipoAtividade: "87 - RETIRAR EMTA", valor: 0 },
  { tipo: "SERVIÇOS", tipoAtividade: "94 - REINSTALACAO - ASSINATURA VOIP", valor: 103.58 },
  { tipo: "ADESÃO", tipoAtividade: "95 - ADESAO - INSTALAR PONTO VOIP", valor: 200.81 },
  { tipo: "SERVIÇOS", tipoAtividade: "96 - INSTALACAO EXTENSAO VOIP", valor: 0 },
  { tipo: "SERVIÇOS", tipoAtividade: "99 - TROCA DE EQUIPAMENTO WIFI", valor: 0 },
  { tipo: "SERVIÇOS", tipoAtividade: "102 - INSTALAR PONTO PORTABILIDADE", valor: 140.56 },
  { tipo: "VISITA TÉCNICA", tipoAtividade: "129 - MANUTENCAO REPARO NO DROP", valor: 0 },
  { tipo: "VISITA TÉCNICA", tipoAtividade: "131 - VISITA TECNICA CUMPRIMENTO ESPECIAL", valor: 0 },
  { tipo: "VISITA TÉCNICA", tipoAtividade: "144 - MANUTENCAO CORRETIVA - DEGRADACAO MDU", valor: 0 },
  { tipo: "SERVIÇOS", tipoAtividade: "148 - TROCA DECODER PARA ATUALIZACAO DIGITAL", valor: 93.49 },
  { tipo: "SERVIÇOS", tipoAtividade: "149 - INSTALAR CABEAMENTO MESH", valor: 25.9 },
  { tipo: "SERVIÇOS", tipoAtividade: "154 - DESOBSTRUCAO - INSTALACAO DE ASSINATURA", valor: 0 },
  { tipo: "SERVIÇOS", tipoAtividade: "156 - INSTALACAO WIFI MESH", valor: 63.23 },
  { tipo: "VISITA TÉCNICA", tipoAtividade: "158 - VISITA TECNICA WIFI MESH", valor: 0 },
  { tipo: "VISITA TÉCNICA", tipoAtividade: "161 - VISITA TECNICA STREAMING", valor: 0 },
  { tipo: "SERVIÇOS", tipoAtividade: "172 - INST PONTO EXTENSAO REDE VIRTUA", valor: 169.17 },
  { tipo: "RETIRADA DE EQUIPAMENTO", tipoAtividade: "173 - RETIRADA WIFI MESH", valor: 0 },
  { tipo: "VISITA TÉCNICA", tipoAtividade: "174 - MANUTENCAO CORRETIVA - MDU GPON", valor: 0 },
  { tipo: "STREAMING", tipoAtividade: "175 - CONFIGURACAO STREAMING", valor: 77.68 },
  { tipo: "SERVIÇOS", tipoAtividade: "176 - REFAZER MANUTENCAO PON", valor: 220.1 },
  { tipo: "SERVIÇOS", tipoAtividade: "178 - TROCA DECODER PARA ATUALIZACAO DIGITAL 4K", valor: 0 },
  { tipo: "VISITA TÉCNICA", tipoAtividade: "180 - MANUTENCAO INDOOR GPON", valor: 0 },
  { tipo: "VISITA TÉCNICA", tipoAtividade: "188 - MANUTENCAO PREVENTIVA INDOOR I", valor: 101.72 },
  { tipo: "SERVIÇOS", tipoAtividade: "190 - INSTALACAO DE CABO HFC", valor: 163.23 },
  { tipo: "SERVIÇOS", tipoAtividade: "191 - INSTALACAO DE CABO GPON", valor: 195.64 },
  { tipo: "ENVIO DE CHIP", tipoAtividade: "208 - ENVIO DE CHIP VIA TECNICO", valor: 0 },
  { tipo: "SERVIÇOS", tipoAtividade: "209 - REFAZER MANUTENCAO", valor: 220.1 },
  { tipo: "VISITA TÉCNICA", tipoAtividade: "211 - MANUTENCAO RETORNO COP", valor: 0 },
  { tipo: "SERVIÇOS", tipoAtividade: "213 - TROCA DE EQUIPAMENTO HD", valor: 38.84 },
  { tipo: "SERVIÇOS", tipoAtividade: "225 - VISTORIA DE CASOS ESPECIAIS IAT", valor: 0 },
  { tipo: "SERVIÇOS", tipoAtividade: "240 - INSTALAR TV BASE", valor: 133.87 },
  { tipo: "SERVIÇOS", tipoAtividade: "261 - VISTORIA DE CASOS ESPECIAIS EPO", valor: 0 },
  { tipo: "STREAMING", tipoAtividade: "304 - TROCA DE EQUIPAMENTO STREAMING", valor: 0 },
  { tipo: "STREAMING", tipoAtividade: "305 - SUBS CONTROLE REMOTO STREAMING", valor: 0 },
  { tipo: "VISITA TÉCNICA", tipoAtividade: "307 - LIMPEZA DE RUIDO INDOOR", valor: 0 },
  { tipo: "STREAMING", tipoAtividade: "510 - BASE ENTREGA STREAMING", valor: 0 },
  { tipo: "MUDANÇA DE PACOTE", tipoAtividade: "511 - MUD PACOTE ENTREGA STREAMING", valor: 0 },
  { tipo: "STREAMING", tipoAtividade: "512 - REINSTALACAO ENTREGA STREAMING", valor: 0 },
  { tipo: "MUDANÇA DE ENDEREÇO", tipoAtividade: "514 - MUDANCA DE ENDERECO - ENTREGA STREAMING", valor: 181.63 },
  { tipo: "ADESÃO", tipoAtividade: "516 - ADESAO ENTREGA STREAMING", valor: 38.85 },
  { tipo: "ADESÃO", tipoAtividade: "517 - ADESAO ENTREGA ADC STREAMING", valor: 38.85 },
  { tipo: "STREAMING", tipoAtividade: "518 - BASE ENTREGA ADC STREAMING", valor: 0 },
];
