/**
 * Catálogo de atividades TOA (aba "Atividade TOA").
 * Tipo = RESUMO; Tipo de Atividade = ATIVIDADES NO TOA.
 * Valores iniciais em 0 — editáveis no modal de preços.
 */
export type AtividadeToaCatalogo = {
  tipo: string;
  tipoAtividade: string;
};

export const ATIVIDADES_TOA_CATALOGO: AtividadeToaCatalogo[] = [
  { tipo: "MUDANÇA DE PACOTE", tipoAtividade: "24 - MUDANCA DE PACOTE" },
  { tipo: "ADESÃO", tipoAtividade: "43 - ADESAO - INSTALAR PONTO VIRTUA" },
  { tipo: "SERVIÇOS", tipoAtividade: "156 - INSTALACAO WIFI MESH" },
  { tipo: "MUDANÇA DE ENDEREÇO", tipoAtividade: "12 - MUDANCA DE ENDERECO - INSTALAR ASSINATURA" },
  { tipo: "VISITA TÉCNICA", tipoAtividade: "48 - VISITA TECNICA - VIRTUA" },
  { tipo: "ADESÃO", tipoAtividade: "1 - ADESAO - INSTALACAO DE ASSINATURA" },
  { tipo: "ADESÃO", tipoAtividade: "516 - ADESAO ENTREGA STREAMING" },
  { tipo: "VISITA TÉCNICA", tipoAtividade: "161 - VISITA TECNICA STREAMING" },
  { tipo: "SERVIÇOS", tipoAtividade: "261 - VISTORIA DE CASOS ESPECIAIS EPO" },
  { tipo: "SERVIÇOS", tipoAtividade: "31 - REFAZER INSTALACAO" },
  { tipo: "RETORNO", tipoAtividade: "69 - RETORNO DE CREDENCIADA" },
  { tipo: "SERVIÇOS", tipoAtividade: "44 - INSTALAR PONTO VIRTUA" },
  { tipo: "VISITA TÉCNICA", tipoAtividade: "158 - VISITA TECNICA WIFI MESH" },
  { tipo: "VISITA TÉCNICA", tipoAtividade: "50 - VISITA TECNICA - VOIP" },
  { tipo: "MUDANÇA DE PACOTE", tipoAtividade: "57 - MUDANCA DE PACOTE DIGITAL" },
  { tipo: "SERVIÇOS", tipoAtividade: "15 - MUDANCA DE LOCAL DE PONTO" },
  { tipo: "VISITA TÉCNICA", tipoAtividade: "211 - MANUTENCAO RETORNO COP" },
  { tipo: "SERVIÇOS", tipoAtividade: "33 - REINSTALACAO - ASSINATURA" },
  { tipo: "STREAMING", tipoAtividade: "512 - REINSTALACAO ENTREGA STREAMING" },
  { tipo: "VISITA TÉCNICA", tipoAtividade: "129 - MANUTENCAO REPARO NO DROP" },
  { tipo: "VISITA TÉCNICA", tipoAtividade: "188 - MANUTENCAO PREVENTIVA INDOOR I" },
  { tipo: "DESCONEXÃO", tipoAtividade: "32 - DESCONEXAO I C/ RETIRADA DE EQUIPAMENTO" },
  { tipo: "STREAMING", tipoAtividade: "510 - BASE ENTREGA STREAMING" },
  { tipo: "RETIRADA DE EQUIPAMENTO", tipoAtividade: "87 - RETIRAR EMTA" },
  { tipo: "DESCONEXÃO", tipoAtividade: "79 - DESCONEXAO OPCAO C/ RETIRADA DE EQUIPAMENTO" },
  { tipo: "RETIRADA DE EQUIPAMENTO", tipoAtividade: "5 - RETIRAR EQUIPAMENTO" },
  { tipo: "RETIRADA DE EQUIPAMENTO", tipoAtividade: "173 - RETIRADA WIFI MESH" },
  { tipo: "STREAMING", tipoAtividade: "305 - SUBS CONTROLE REMOTO STREAMING" },
  { tipo: "RETIRADA DE PONTO", tipoAtividade: "4 - RETIRAR PONTO" },
  { tipo: "STREAMING", tipoAtividade: "304 - TROCA DE EQUIPAMENTO STREAMING" },
  { tipo: "SERVIÇOS", tipoAtividade: "240 - INSTALAR TV BASE" },
  { tipo: "MUDANÇA DE ENDEREÇO", tipoAtividade: "514 - MUDANCA DE ENDERECO - ENTREGA STREAMING" },
  { tipo: "SERVIÇOS", tipoAtividade: "83 - INSTALAR PONTO VOIP" },
  { tipo: "SERVIÇOS", tipoAtividade: "225 - VISTORIA DE CASOS ESPECIAIS IAT" },
  { tipo: "SERVIÇOS", tipoAtividade: "99 - TROCA DE EQUIPAMENTO WIFI" },
  { tipo: "SERVIÇOS", tipoAtividade: "56 - MUDANCA DE LOCAL DE PONTO DIGITAL" },
  { tipo: "SERVIÇOS", tipoAtividade: "172 - INST PONTO EXTENSAO REDE VIRTUA" },
  { tipo: "STREAMING", tipoAtividade: "518 - BASE ENTREGA ADC STREAMING" },
  { tipo: "SERVIÇOS", tipoAtividade: "209 - REFAZER MANUTENCAO" },
  { tipo: "SERVIÇOS", tipoAtividade: "176 - REFAZER MANUTENCAO PON" },
  { tipo: "VISITA TÉCNICA", tipoAtividade: "62 - VISITA TECNICA DIGITAL" },
  { tipo: "SERVIÇOS", tipoAtividade: "213 - TROCA DE EQUIPAMENTO HD" },
  { tipo: "SERVIÇOS", tipoAtividade: "148 - TROCA DECODER PARA ATUALIZACAO DIGITAL" },
  { tipo: "SERVIÇOS", tipoAtividade: "154 - DESOBSTRUCAO - INSTALACAO DE ASSINATURA" },
  { tipo: "ADESÃO", tipoAtividade: "51 - ADESAO - INSTALACAO DE ASSINATURA DIGITAL" },
  { tipo: "MUDANÇA DE ENDEREÇO", tipoAtividade: "54 - MUDANCA DE ENDERECO - INSTALAR ASSINATURA DIGITAL" },
  { tipo: "VISITA TÉCNICA", tipoAtividade: "307 - LIMPEZA DE RUIDO INDOOR" },
  { tipo: "SERVIÇOS", tipoAtividade: "96 - INSTALACAO EXTENSAO VOIP" },
  { tipo: "SERVIÇOS", tipoAtividade: "53 - INSTALAR SERVICO CONEXAO ADICIONAL DIGITAL" },
  { tipo: "STREAMING", tipoAtividade: "175 - CONFIGURACAO STREAMING" },
  { tipo: "SERVIÇOS", tipoAtividade: "59 - REINSTALACAO - ASSINATURA DIGITAL" },
  { tipo: "SERVIÇOS", tipoAtividade: "102 - INSTALAR PONTO PORTABILIDADE" },
  { tipo: "VISITA TÉCNICA", tipoAtividade: "180 - MANUTENCAO INDOOR GPON" },
  { tipo: "SERVIÇOS", tipoAtividade: "178 - TROCA DECODER PARA ATUALIZACAO DIGITAL 4K" },
  { tipo: "MUDANÇA DE PACOTE", tipoAtividade: "511 - MUD PACOTE ENTREGA STREAMING" },
  { tipo: "SERVIÇOS", tipoAtividade: "191 - INSTALACAO DE CABO GPON" },
  { tipo: "VISITA TÉCNICA", tipoAtividade: "144 - MANUTENCAO CORRETIVA - DEGRADACAO MDU" },
  { tipo: "ENVIO DE CHIP", tipoAtividade: "208 - ENVIO DE CHIP VIA TECNICO" },
  { tipo: "SERVIÇOS", tipoAtividade: "46 - REINSTALACAO - PONTO ADICIONAL VIRTUA" },
  { tipo: "MUDANÇA DE ENDEREÇO", tipoAtividade: "45 - MUDANCA DE ENDERECO - INSTALAR PONTO ADICIONAL VIRTUA" },
  { tipo: "SERVIÇOS", tipoAtividade: "94 - REINSTALACAO - ASSINATURA VOIP" },
  { tipo: "VISITA TÉCNICA", tipoAtividade: "174 - MANUTENCAO CORRETIVA - MDU GPON" },
  { tipo: "VISITA TÉCNICA", tipoAtividade: "131 - VISITA TECNICA CUMPRIMENTO ESPECIAL" },
  { tipo: "ADESÃO", tipoAtividade: "517 - ADESAO ENTREGA ADC STREAMING" },
  { tipo: "VISITA TÉCNICA", tipoAtividade: "131 - VISITA TECNICA CUMPRIMENTO ESPECIAL" },
];
