/**
 * Catálogo oficial de preços TOA calibrado no Analítico Claro (dez/25–jun/26).
 * Valor = média histórica (tipos variáveis) ou valor fixo (tipos estáveis).
 * Atividades nunca pagas no gabarito ficam em 0. Editáveis no modal.
 */
export type AtividadeToaCatalogo = {
  tipo: string;
  tipoAtividade: string;
  valor: number;
};

export const ATIVIDADES_TOA_CATALOGO: AtividadeToaCatalogo[] = [
  { tipo: "ADESÃO", tipoAtividade: "1 - ADESAO - INSTALACAO DE ASSINATURA", valor: 213.13 },
  { tipo: "RETIRADA DE PONTO", tipoAtividade: "4 - RETIRAR PONTO", valor: 25.71 },
  { tipo: "RETIRADA DE EQUIPAMENTO", tipoAtividade: "5 - RETIRAR EQUIPAMENTO", valor: 0 },
  { tipo: "MUDANÇA DE ENDEREÇO", tipoAtividade: "12 - MUDANCA DE ENDERECO - INSTALAR ASSINATURA", valor: 184.16 },
  { tipo: "SERVIÇOS", tipoAtividade: "15 - MUDANCA DE LOCAL DE PONTO", valor: 167.07 },
  { tipo: "MUDANÇA DE PACOTE", tipoAtividade: "24 - MUDANCA DE PACOTE", valor: 93.64 },
  { tipo: "SERVIÇOS", tipoAtividade: "31 - REFAZER INSTALACAO", valor: 218.48 },
  { tipo: "DESCONEXÃO", tipoAtividade: "32 - DESCONEXAO I C/ RETIRADA DE EQUIPAMENTO", valor: 0 },
  { tipo: "SERVIÇOS", tipoAtividade: "33 - REINSTALACAO - ASSINATURA", valor: 115.67 },
  { tipo: "ADESÃO", tipoAtividade: "43 - ADESAO - INSTALAR PONTO VIRTUA", valor: 211.68 },
  { tipo: "SERVIÇOS", tipoAtividade: "44 - INSTALAR PONTO VIRTUA", valor: 175.56 },
  { tipo: "MUDANÇA DE ENDEREÇO", tipoAtividade: "45 - MUDANCA DE ENDERECO - INSTALAR PONTO ADICIONAL VIRTUA", valor: 0 },
  { tipo: "SERVIÇOS", tipoAtividade: "46 - REINSTALACAO - PONTO ADICIONAL VIRTUA", valor: 77.11 },
  { tipo: "VISITA TÉCNICA", tipoAtividade: "48 - VISITA TECNICA - VIRTUA", valor: 0 },
  { tipo: "VISITA TÉCNICA", tipoAtividade: "50 - VISITA TECNICA - VOIP", valor: 0 },
  { tipo: "ADESÃO", tipoAtividade: "51 - ADESAO - INSTALACAO DE ASSINATURA DIGITAL", valor: 257.8 },
  { tipo: "ADESÃO", tipoAtividade: "52 - ADESAO - INSTALAR SERVICO CONEXAO ADICIONAL DIGITAL", valor: 66.44 },
  { tipo: "SERVIÇOS", tipoAtividade: "53 - INSTALAR SERVICO CONEXAO ADICIONAL DIGITAL", valor: 146.17 },
  { tipo: "MUDANÇA DE ENDEREÇO", tipoAtividade: "54 - MUDANCA DE ENDERECO - INSTALAR ASSINATURA DIGITAL", valor: 205.77 },
  { tipo: "MUDANÇA DE ENDEREÇO", tipoAtividade: "55 - MUDANCA ENDERECO - INSTALAR SERVICO CONEXAO ADIC DIG", valor: 64.26 },
  { tipo: "SERVIÇOS", tipoAtividade: "56 - MUDANCA DE LOCAL DE PONTO DIGITAL", valor: 167.07 },
  { tipo: "MUDANÇA DE PACOTE", tipoAtividade: "57 - MUDANCA DE PACOTE DIGITAL", valor: 98.81 },
  { tipo: "SERVIÇOS", tipoAtividade: "59 - REINSTALACAO - ASSINATURA DIGITAL", valor: 115.67 },
  { tipo: "VISITA TÉCNICA", tipoAtividade: "62 - VISITA TECNICA DIGITAL", valor: 0 },
  { tipo: "RETORNO", tipoAtividade: "69 - RETORNO DE CREDENCIADA", valor: 0 },
  { tipo: "DESCONEXÃO", tipoAtividade: "79 - DESCONEXAO OPCAO C/ RETIRADA DE EQUIPAMENTO", valor: 0 },
  { tipo: "SERVIÇOS", tipoAtividade: "83 - INSTALAR PONTO VOIP", valor: 123.1 },
  { tipo: "RETIRADA DE EQUIPAMENTO", tipoAtividade: "87 - RETIRAR EMTA", valor: 0 },
  { tipo: "SERVIÇOS", tipoAtividade: "94 - REINSTALACAO - ASSINATURA VOIP", valor: 102.82 },
  { tipo: "ADESÃO", tipoAtividade: "95 - ADESAO - INSTALAR PONTO VOIP", valor: 199.33 },
  { tipo: "SERVIÇOS", tipoAtividade: "96 - INSTALACAO EXTENSAO VOIP", valor: 0 },
  { tipo: "SERVIÇOS", tipoAtividade: "99 - TROCA DE EQUIPAMENTO WIFI", valor: 0 },
  { tipo: "SERVIÇOS", tipoAtividade: "102 - INSTALAR PONTO PORTABILIDADE", valor: 139.53 },
  { tipo: "VISITA TÉCNICA", tipoAtividade: "129 - MANUTENCAO REPARO NO DROP", valor: 0 },
  { tipo: "VISITA TÉCNICA", tipoAtividade: "131 - VISITA TECNICA CUMPRIMENTO ESPECIAL", valor: 0 },
  { tipo: "VISITA TÉCNICA", tipoAtividade: "144 - MANUTENCAO CORRETIVA - DEGRADACAO MDU", valor: 0 },
  { tipo: "SERVIÇOS", tipoAtividade: "148 - TROCA DECODER PARA ATUALIZACAO DIGITAL", valor: 92.8 },
  { tipo: "SERVIÇOS", tipoAtividade: "149 - INSTALAR CABEAMENTO MESH", valor: 25.71 },
  { tipo: "SERVIÇOS", tipoAtividade: "154 - DESOBSTRUCAO - INSTALACAO DE ASSINATURA", valor: 0 },
  { tipo: "SERVIÇOS", tipoAtividade: "156 - INSTALACAO WIFI MESH", valor: 62.76 },
  { tipo: "VISITA TÉCNICA", tipoAtividade: "158 - VISITA TECNICA WIFI MESH", valor: 0 },
  { tipo: "VISITA TÉCNICA", tipoAtividade: "161 - VISITA TECNICA STREAMING", valor: 0 },
  { tipo: "SERVIÇOS", tipoAtividade: "172 - INST PONTO EXTENSAO REDE VIRTUA", valor: 167.93 },
  { tipo: "RETIRADA DE EQUIPAMENTO", tipoAtividade: "173 - RETIRADA WIFI MESH", valor: 0 },
  { tipo: "VISITA TÉCNICA", tipoAtividade: "174 - MANUTENCAO CORRETIVA - MDU GPON", valor: 0 },
  { tipo: "STREAMING", tipoAtividade: "175 - CONFIGURACAO STREAMING", valor: 77.11 },
  { tipo: "SERVIÇOS", tipoAtividade: "176 - REFAZER MANUTENCAO PON", valor: 218.48 },
  { tipo: "SERVIÇOS", tipoAtividade: "178 - TROCA DECODER PARA ATUALIZACAO DIGITAL 4K", valor: 0 },
  { tipo: "VISITA TÉCNICA", tipoAtividade: "180 - MANUTENCAO INDOOR GPON", valor: 0 },
  { tipo: "VISITA TÉCNICA", tipoAtividade: "188 - MANUTENCAO PREVENTIVA INDOOR I", valor: 100.97 },
  { tipo: "SERVIÇOS", tipoAtividade: "190 - INSTALACAO DE CABO HFC", valor: 162.03 },
  { tipo: "SERVIÇOS", tipoAtividade: "191 - INSTALACAO DE CABO GPON", valor: 194.2 },
  { tipo: "ENVIO DE CHIP", tipoAtividade: "208 - ENVIO DE CHIP VIA TECNICO", valor: 0 },
  { tipo: "SERVIÇOS", tipoAtividade: "209 - REFAZER MANUTENCAO", valor: 218.48 },
  { tipo: "VISITA TÉCNICA", tipoAtividade: "211 - MANUTENCAO RETORNO COP", valor: 0 },
  { tipo: "SERVIÇOS", tipoAtividade: "213 - TROCA DE EQUIPAMENTO HD", valor: 38.55 },
  { tipo: "SERVIÇOS", tipoAtividade: "225 - VISTORIA DE CASOS ESPECIAIS IAT", valor: 0 },
  { tipo: "SERVIÇOS", tipoAtividade: "240 - INSTALAR TV BASE", valor: 132.88 },
  { tipo: "SERVIÇOS", tipoAtividade: "261 - VISTORIA DE CASOS ESPECIAIS EPO", valor: 0 },
  { tipo: "STREAMING", tipoAtividade: "304 - TROCA DE EQUIPAMENTO STREAMING", valor: 0 },
  { tipo: "STREAMING", tipoAtividade: "305 - SUBS CONTROLE REMOTO STREAMING", valor: 0 },
  { tipo: "VISITA TÉCNICA", tipoAtividade: "307 - LIMPEZA DE RUIDO INDOOR", valor: 0 },
  { tipo: "STREAMING", tipoAtividade: "510 - BASE ENTREGA STREAMING", valor: 0 },
  { tipo: "MUDANÇA DE PACOTE", tipoAtividade: "511 - MUD PACOTE ENTREGA STREAMING", valor: 0 },
  { tipo: "STREAMING", tipoAtividade: "512 - REINSTALACAO ENTREGA STREAMING", valor: 0 },
  { tipo: "MUDANÇA DE ENDEREÇO", tipoAtividade: "514 - MUDANCA DE ENDERECO - ENTREGA STREAMING", valor: 180.29 },
  { tipo: "ADESÃO", tipoAtividade: "516 - ADESAO ENTREGA STREAMING", valor: 38.56 },
  { tipo: "ADESÃO", tipoAtividade: "517 - ADESAO ENTREGA ADC STREAMING", valor: 38.56 },
  { tipo: "STREAMING", tipoAtividade: "518 - BASE ENTREGA ADC STREAMING", valor: 0 },
];
