/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodosRouteImport } from './routes/todos'
import { Route as TecnicosRouteImport } from './routes/tecnicos'
import { Route as PrevisaoReservaRouteImport } from './routes/previsao-reserva'
import { Route as MetragemRouteImport } from './routes/metragem'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as EstoqueFisicoBtpRouteImport } from './routes/estoque-fisico-btp'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AlterarRouteImport } from './routes/alterar'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminPendenciasRouteImport } from './routes/admin/pendencias'
import { Route as AdminKpisRouteImport } from './routes/admin/kpis'
import { Route as AdminImportacaoRouteImport } from './routes/admin/importacao'
import { Route as AdminEnviarEvidenciaRouteImport } from './routes/admin/enviar-evidencia'
import { Route as ApiEvidenciasSubmitRouteImport } from './routes/api/evidencias.submit'
import { Route as ApiEvidenciasNotifyEmailRouteImport } from './routes/api/evidencias.notify-email'
import { Route as ApiEvidenciasBatchSubmitRouteImport } from './routes/api/evidencias.batch-submit'
import { Route as ApiEvidenciasAdminSubmitRouteImport } from './routes/api/evidencias.admin-submit'

const TodosRoute = TodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => rootRouteImport,
} as any)
const TecnicosRoute = TecnicosRouteImport.update({
  id: '/tecnicos',
  path: '/tecnicos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrevisaoReservaRoute = PrevisaoReservaRouteImport.update({
  id: '/previsao-reserva',
  path: '/previsao-reserva',
  getParentRoute: () => rootRouteImport,
} as any)
const MetragemRoute = MetragemRouteImport.update({
  id: '/metragem',
  path: '/metragem',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueFisicoBtpRoute = EstoqueFisicoBtpRouteImport.update({
  id: '/estoque-fisico-btp',
  path: '/estoque-fisico-btp',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AlterarRoute = AlterarRouteImport.update({
  id: '/alterar',
  path: '/alterar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPendenciasRoute = AdminPendenciasRouteImport.update({
  id: '/pendencias',
  path: '/pendencias',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKpisRoute = AdminKpisRouteImport.update({
  id: '/kpis',
  path: '/kpis',
  getParentRoute: () => AdminRoute,
} as any)
const AdminImportacaoRoute = AdminImportacaoRouteImport.update({
  id: '/importacao',
  path: '/importacao',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEnviarEvidenciaRoute = AdminEnviarEvidenciaRouteImport.update({
  id: '/enviar-evidencia',
  path: '/enviar-evidencia',
  getParentRoute: () => AdminRoute,
} as any)
const ApiEvidenciasSubmitRoute = ApiEvidenciasSubmitRouteImport.update({
  id: '/api/evidencias/submit',
  path: '/api/evidencias/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEvidenciasNotifyEmailRoute =
  ApiEvidenciasNotifyEmailRouteImport.update({
    id: '/api/evidencias/notify-email',
    path: '/api/evidencias/notify-email',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiEvidenciasBatchSubmitRoute =
  ApiEvidenciasBatchSubmitRouteImport.update({
    id: '/api/evidencias/batch-submit',
    path: '/api/evidencias/batch-submit',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiEvidenciasAdminSubmitRoute =
  ApiEvidenciasAdminSubmitRouteImport.update({
    id: '/api/evidencias/admin-submit',
    path: '/api/evidencias/admin-submit',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/alterar': typeof AlterarRoute
  '/cadastro': typeof CadastroRoute
  '/estoque-fisico-btp': typeof EstoqueFisicoBtpRoute
  '/historico': typeof HistoricoRoute
  '/login': typeof LoginRoute
  '/metragem': typeof MetragemRoute
  '/previsao-reserva': typeof PrevisaoReservaRoute
  '/tecnicos': typeof TecnicosRoute
  '/todos': typeof TodosRoute
  '/admin/enviar-evidencia': typeof AdminEnviarEvidenciaRoute
  '/admin/importacao': typeof AdminImportacaoRoute
  '/admin/kpis': typeof AdminKpisRoute
  '/admin/pendencias': typeof AdminPendenciasRoute
  '/admin/': typeof AdminIndexRoute
  '/api/evidencias/admin-submit': typeof ApiEvidenciasAdminSubmitRoute
  '/api/evidencias/batch-submit': typeof ApiEvidenciasBatchSubmitRoute
  '/api/evidencias/notify-email': typeof ApiEvidenciasNotifyEmailRoute
  '/api/evidencias/submit': typeof ApiEvidenciasSubmitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alterar': typeof AlterarRoute
  '/cadastro': typeof CadastroRoute
  '/estoque-fisico-btp': typeof EstoqueFisicoBtpRoute
  '/historico': typeof HistoricoRoute
  '/login': typeof LoginRoute
  '/metragem': typeof MetragemRoute
  '/previsao-reserva': typeof PrevisaoReservaRoute
  '/tecnicos': typeof TecnicosRoute
  '/todos': typeof TodosRoute
  '/admin/enviar-evidencia': typeof AdminEnviarEvidenciaRoute
  '/admin/importacao': typeof AdminImportacaoRoute
  '/admin/kpis': typeof AdminKpisRoute
  '/admin/pendencias': typeof AdminPendenciasRoute
  '/admin': typeof AdminIndexRoute
  '/api/evidencias/admin-submit': typeof ApiEvidenciasAdminSubmitRoute
  '/api/evidencias/batch-submit': typeof ApiEvidenciasBatchSubmitRoute
  '/api/evidencias/notify-email': typeof ApiEvidenciasNotifyEmailRoute
  '/api/evidencias/submit': typeof ApiEvidenciasSubmitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/alterar': typeof AlterarRoute
  '/cadastro': typeof CadastroRoute
  '/estoque-fisico-btp': typeof EstoqueFisicoBtpRoute
  '/historico': typeof HistoricoRoute
  '/login': typeof LoginRoute
  '/metragem': typeof MetragemRoute
  '/previsao-reserva': typeof PrevisaoReservaRoute
  '/tecnicos': typeof TecnicosRoute
  '/todos': typeof TodosRoute
  '/admin/enviar-evidencia': typeof AdminEnviarEvidenciaRoute
  '/admin/importacao': typeof AdminImportacaoRoute
  '/admin/kpis': typeof AdminKpisRoute
  '/admin/pendencias': typeof AdminPendenciasRoute
  '/admin/': typeof AdminIndexRoute
  '/api/evidencias/admin-submit': typeof ApiEvidenciasAdminSubmitRoute
  '/api/evidencias/batch-submit': typeof ApiEvidenciasBatchSubmitRoute
  '/api/evidencias/notify-email': typeof ApiEvidenciasNotifyEmailRoute
  '/api/evidencias/submit': typeof ApiEvidenciasSubmitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/alterar'
    | '/cadastro'
    | '/estoque-fisico-btp'
    | '/historico'
    | '/login'
    | '/metragem'
    | '/previsao-reserva'
    | '/tecnicos'
    | '/todos'
    | '/admin/enviar-evidencia'
    | '/admin/importacao'
    | '/admin/kpis'
    | '/admin/pendencias'
    | '/admin/'
    | '/api/evidencias/admin-submit'
    | '/api/evidencias/batch-submit'
    | '/api/evidencias/notify-email'
    | '/api/evidencias/submit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alterar'
    | '/cadastro'
    | '/estoque-fisico-btp'
    | '/historico'
    | '/login'
    | '/metragem'
    | '/previsao-reserva'
    | '/tecnicos'
    | '/todos'
    | '/admin/enviar-evidencia'
    | '/admin/importacao'
    | '/admin/kpis'
    | '/admin/pendencias'
    | '/admin'
    | '/api/evidencias/admin-submit'
    | '/api/evidencias/batch-submit'
    | '/api/evidencias/notify-email'
    | '/api/evidencias/submit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/alterar'
    | '/cadastro'
    | '/estoque-fisico-btp'
    | '/historico'
    | '/login'
    | '/metragem'
    | '/previsao-reserva'
    | '/tecnicos'
    | '/todos'
    | '/admin/enviar-evidencia'
    | '/admin/importacao'
    | '/admin/kpis'
    | '/admin/pendencias'
    | '/admin/'
    | '/api/evidencias/admin-submit'
    | '/api/evidencias/batch-submit'
    | '/api/evidencias/notify-email'
    | '/api/evidencias/submit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AlterarRoute: typeof AlterarRoute
  CadastroRoute: typeof CadastroRoute
  EstoqueFisicoBtpRoute: typeof EstoqueFisicoBtpRoute
  HistoricoRoute: typeof HistoricoRoute
  LoginRoute: typeof LoginRoute
  MetragemRoute: typeof MetragemRoute
  PrevisaoReservaRoute: typeof PrevisaoReservaRoute
  TecnicosRoute: typeof TecnicosRoute
  TodosRoute: typeof TodosRoute
  ApiEvidenciasAdminSubmitRoute: typeof ApiEvidenciasAdminSubmitRoute
  ApiEvidenciasBatchSubmitRoute: typeof ApiEvidenciasBatchSubmitRoute
  ApiEvidenciasNotifyEmailRoute: typeof ApiEvidenciasNotifyEmailRoute
  ApiEvidenciasSubmitRoute: typeof ApiEvidenciasSubmitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/todos': {
      id: '/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof TodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tecnicos': {
      id: '/tecnicos'
      path: '/tecnicos'
      fullPath: '/tecnicos'
      preLoaderRoute: typeof TecnicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/previsao-reserva': {
      id: '/previsao-reserva'
      path: '/previsao-reserva'
      fullPath: '/previsao-reserva'
      preLoaderRoute: typeof PrevisaoReservaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metragem': {
      id: '/metragem'
      path: '/metragem'
      fullPath: '/metragem'
      preLoaderRoute: typeof MetragemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque-fisico-btp': {
      id: '/estoque-fisico-btp'
      path: '/estoque-fisico-btp'
      fullPath: '/estoque-fisico-btp'
      preLoaderRoute: typeof EstoqueFisicoBtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alterar': {
      id: '/alterar'
      path: '/alterar'
      fullPath: '/alterar'
      preLoaderRoute: typeof AlterarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pendencias': {
      id: '/admin/pendencias'
      path: '/pendencias'
      fullPath: '/admin/pendencias'
      preLoaderRoute: typeof AdminPendenciasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kpis': {
      id: '/admin/kpis'
      path: '/kpis'
      fullPath: '/admin/kpis'
      preLoaderRoute: typeof AdminKpisRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/importacao': {
      id: '/admin/importacao'
      path: '/importacao'
      fullPath: '/admin/importacao'
      preLoaderRoute: typeof AdminImportacaoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/enviar-evidencia': {
      id: '/admin/enviar-evidencia'
      path: '/enviar-evidencia'
      fullPath: '/admin/enviar-evidencia'
      preLoaderRoute: typeof AdminEnviarEvidenciaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/evidencias/submit': {
      id: '/api/evidencias/submit'
      path: '/api/evidencias/submit'
      fullPath: '/api/evidencias/submit'
      preLoaderRoute: typeof ApiEvidenciasSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/evidencias/notify-email': {
      id: '/api/evidencias/notify-email'
      path: '/api/evidencias/notify-email'
      fullPath: '/api/evidencias/notify-email'
      preLoaderRoute: typeof ApiEvidenciasNotifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/evidencias/batch-submit': {
      id: '/api/evidencias/batch-submit'
      path: '/api/evidencias/batch-submit'
      fullPath: '/api/evidencias/batch-submit'
      preLoaderRoute: typeof ApiEvidenciasBatchSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/evidencias/admin-submit': {
      id: '/api/evidencias/admin-submit'
      path: '/api/evidencias/admin-submit'
      fullPath: '/api/evidencias/admin-submit'
      preLoaderRoute: typeof ApiEvidenciasAdminSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminEnviarEvidenciaRoute: typeof AdminEnviarEvidenciaRoute
  AdminImportacaoRoute: typeof AdminImportacaoRoute
  AdminKpisRoute: typeof AdminKpisRoute
  AdminPendenciasRoute: typeof AdminPendenciasRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminEnviarEvidenciaRoute: AdminEnviarEvidenciaRoute,
  AdminImportacaoRoute: AdminImportacaoRoute,
  AdminKpisRoute: AdminKpisRoute,
  AdminPendenciasRoute: AdminPendenciasRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AlterarRoute: AlterarRoute,
  CadastroRoute: CadastroRoute,
  EstoqueFisicoBtpRoute: EstoqueFisicoBtpRoute,
  HistoricoRoute: HistoricoRoute,
  LoginRoute: LoginRoute,
  MetragemRoute: MetragemRoute,
  PrevisaoReservaRoute: PrevisaoReservaRoute,
  TecnicosRoute: TecnicosRoute,
  TodosRoute: TodosRoute,
  ApiEvidenciasAdminSubmitRoute: ApiEvidenciasAdminSubmitRoute,
  ApiEvidenciasBatchSubmitRoute: ApiEvidenciasBatchSubmitRoute,
  ApiEvidenciasNotifyEmailRoute: ApiEvidenciasNotifyEmailRoute,
  ApiEvidenciasSubmitRoute: ApiEvidenciasSubmitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
