/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodosRouteImport } from './routes/todos'
import { Route as TecnicosRouteImport } from './routes/tecnicos'
import { Route as RelatorioRouteImport } from './routes/relatorio'
import { Route as PrevisaoReservaRouteImport } from './routes/previsao-reserva'
import { Route as MetragemRouteImport } from './routes/metragem'
import { Route as MediaBaixaTecnicoRouteImport } from './routes/media-baixa-tecnico'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as EstoqueTecnicoRouteImport } from './routes/estoque-tecnico'
import { Route as EstoqueFisicoBtpRouteImport } from './routes/estoque-fisico-btp'
import { Route as EstoqueBaseRouteImport } from './routes/estoque-base'
import { Route as EstoqueAtlasRouteImport } from './routes/estoque-atlas'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AlterarRouteImport } from './routes/alterar'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminPendenciasRouteImport } from './routes/admin/pendencias'
import { Route as AdminImportacaoRouteImport } from './routes/admin/importacao'
import { Route as AdminEnviarEvidenciaRouteImport } from './routes/admin/enviar-evidencia'
import { Route as AdminLancamentosIndexRouteImport } from './routes/admin/lancamentos/index'
import { Route as AdminKpisIndexRouteImport } from './routes/admin/kpis/index'
import { Route as ApiEvidenciasTestEmailRouteImport } from './routes/api/evidencias.test-email'
import { Route as ApiEvidenciasSubmitRouteImport } from './routes/api/evidencias.submit'
import { Route as ApiEvidenciasNotifyEmailRouteImport } from './routes/api/evidencias.notify-email'
import { Route as ApiEvidenciasBatchSubmitRouteImport } from './routes/api/evidencias.batch-submit'
import { Route as ApiEvidenciasAdminSubmitRouteImport } from './routes/api/evidencias.admin-submit'
import { Route as AdminLancamentosIdRouteImport } from './routes/admin/lancamentos/$id'
import { Route as AdminKpisModuloRouteImport } from './routes/admin/kpis/$modulo'

const TodosRoute = TodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => rootRouteImport,
} as any)
const TecnicosRoute = TecnicosRouteImport.update({
  id: '/tecnicos',
  path: '/tecnicos',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatorioRoute = RelatorioRouteImport.update({
  id: '/relatorio',
  path: '/relatorio',
  getParentRoute: () => rootRouteImport,
} as any)
const PrevisaoReservaRoute = PrevisaoReservaRouteImport.update({
  id: '/previsao-reserva',
  path: '/previsao-reserva',
  getParentRoute: () => rootRouteImport,
} as any)
const MetragemRoute = MetragemRouteImport.update({
  id: '/metragem',
  path: '/metragem',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaBaixaTecnicoRoute = MediaBaixaTecnicoRouteImport.update({
  id: '/media-baixa-tecnico',
  path: '/media-baixa-tecnico',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueTecnicoRoute = EstoqueTecnicoRouteImport.update({
  id: '/estoque-tecnico',
  path: '/estoque-tecnico',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueFisicoBtpRoute = EstoqueFisicoBtpRouteImport.update({
  id: '/estoque-fisico-btp',
  path: '/estoque-fisico-btp',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueBaseRoute = EstoqueBaseRouteImport.update({
  id: '/estoque-base',
  path: '/estoque-base',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueAtlasRoute = EstoqueAtlasRouteImport.update({
  id: '/estoque-atlas',
  path: '/estoque-atlas',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AlterarRoute = AlterarRouteImport.update({
  id: '/alterar',
  path: '/alterar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPendenciasRoute = AdminPendenciasRouteImport.update({
  id: '/pendencias',
  path: '/pendencias',
  getParentRoute: () => AdminRoute,
} as any)
const AdminImportacaoRoute = AdminImportacaoRouteImport.update({
  id: '/importacao',
  path: '/importacao',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEnviarEvidenciaRoute = AdminEnviarEvidenciaRouteImport.update({
  id: '/enviar-evidencia',
  path: '/enviar-evidencia',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLancamentosIndexRoute = AdminLancamentosIndexRouteImport.update({
  id: '/lancamentos/',
  path: '/lancamentos/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKpisIndexRoute = AdminKpisIndexRouteImport.update({
  id: '/kpis/',
  path: '/kpis/',
  getParentRoute: () => AdminRoute,
} as any)
const ApiEvidenciasTestEmailRoute = ApiEvidenciasTestEmailRouteImport.update({
  id: '/api/evidencias/test-email',
  path: '/api/evidencias/test-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEvidenciasSubmitRoute = ApiEvidenciasSubmitRouteImport.update({
  id: '/api/evidencias/submit',
  path: '/api/evidencias/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEvidenciasNotifyEmailRoute =
  ApiEvidenciasNotifyEmailRouteImport.update({
    id: '/api/evidencias/notify-email',
    path: '/api/evidencias/notify-email',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiEvidenciasBatchSubmitRoute =
  ApiEvidenciasBatchSubmitRouteImport.update({
    id: '/api/evidencias/batch-submit',
    path: '/api/evidencias/batch-submit',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiEvidenciasAdminSubmitRoute =
  ApiEvidenciasAdminSubmitRouteImport.update({
    id: '/api/evidencias/admin-submit',
    path: '/api/evidencias/admin-submit',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminLancamentosIdRoute = AdminLancamentosIdRouteImport.update({
  id: '/lancamentos/$id',
  path: '/lancamentos/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKpisModuloRoute = AdminKpisModuloRouteImport.update({
  id: '/kpis/$modulo',
  path: '/kpis/$modulo',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/alterar': typeof AlterarRoute
  '/cadastro': typeof CadastroRoute
  '/estoque-atlas': typeof EstoqueAtlasRoute
  '/estoque-base': typeof EstoqueBaseRoute
  '/estoque-fisico-btp': typeof EstoqueFisicoBtpRoute
  '/estoque-tecnico': typeof EstoqueTecnicoRoute
  '/historico': typeof HistoricoRoute
  '/login': typeof LoginRoute
  '/media-baixa-tecnico': typeof MediaBaixaTecnicoRoute
  '/metragem': typeof MetragemRoute
  '/previsao-reserva': typeof PrevisaoReservaRoute
  '/relatorio': typeof RelatorioRoute
  '/tecnicos': typeof TecnicosRoute
  '/todos': typeof TodosRoute
  '/admin/enviar-evidencia': typeof AdminEnviarEvidenciaRoute
  '/admin/importacao': typeof AdminImportacaoRoute
  '/admin/pendencias': typeof AdminPendenciasRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/kpis/$modulo': typeof AdminKpisModuloRoute
  '/admin/lancamentos/$id': typeof AdminLancamentosIdRoute
  '/api/evidencias/admin-submit': typeof ApiEvidenciasAdminSubmitRoute
  '/api/evidencias/batch-submit': typeof ApiEvidenciasBatchSubmitRoute
  '/api/evidencias/notify-email': typeof ApiEvidenciasNotifyEmailRoute
  '/api/evidencias/submit': typeof ApiEvidenciasSubmitRoute
  '/api/evidencias/test-email': typeof ApiEvidenciasTestEmailRoute
  '/admin/kpis/': typeof AdminKpisIndexRoute
  '/admin/lancamentos/': typeof AdminLancamentosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alterar': typeof AlterarRoute
  '/cadastro': typeof CadastroRoute
  '/estoque-atlas': typeof EstoqueAtlasRoute
  '/estoque-base': typeof EstoqueBaseRoute
  '/estoque-fisico-btp': typeof EstoqueFisicoBtpRoute
  '/estoque-tecnico': typeof EstoqueTecnicoRoute
  '/historico': typeof HistoricoRoute
  '/login': typeof LoginRoute
  '/media-baixa-tecnico': typeof MediaBaixaTecnicoRoute
  '/metragem': typeof MetragemRoute
  '/previsao-reserva': typeof PrevisaoReservaRoute
  '/relatorio': typeof RelatorioRoute
  '/tecnicos': typeof TecnicosRoute
  '/todos': typeof TodosRoute
  '/admin/enviar-evidencia': typeof AdminEnviarEvidenciaRoute
  '/admin/importacao': typeof AdminImportacaoRoute
  '/admin/pendencias': typeof AdminPendenciasRoute
  '/admin': typeof AdminIndexRoute
  '/admin/kpis/$modulo': typeof AdminKpisModuloRoute
  '/admin/lancamentos/$id': typeof AdminLancamentosIdRoute
  '/api/evidencias/admin-submit': typeof ApiEvidenciasAdminSubmitRoute
  '/api/evidencias/batch-submit': typeof ApiEvidenciasBatchSubmitRoute
  '/api/evidencias/notify-email': typeof ApiEvidenciasNotifyEmailRoute
  '/api/evidencias/submit': typeof ApiEvidenciasSubmitRoute
  '/api/evidencias/test-email': typeof ApiEvidenciasTestEmailRoute
  '/admin/kpis': typeof AdminKpisIndexRoute
  '/admin/lancamentos': typeof AdminLancamentosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/alterar': typeof AlterarRoute
  '/cadastro': typeof CadastroRoute
  '/estoque-atlas': typeof EstoqueAtlasRoute
  '/estoque-base': typeof EstoqueBaseRoute
  '/estoque-fisico-btp': typeof EstoqueFisicoBtpRoute
  '/estoque-tecnico': typeof EstoqueTecnicoRoute
  '/historico': typeof HistoricoRoute
  '/login': typeof LoginRoute
  '/media-baixa-tecnico': typeof MediaBaixaTecnicoRoute
  '/metragem': typeof MetragemRoute
  '/previsao-reserva': typeof PrevisaoReservaRoute
  '/relatorio': typeof RelatorioRoute
  '/tecnicos': typeof TecnicosRoute
  '/todos': typeof TodosRoute
  '/admin/enviar-evidencia': typeof AdminEnviarEvidenciaRoute
  '/admin/importacao': typeof AdminImportacaoRoute
  '/admin/pendencias': typeof AdminPendenciasRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/kpis/$modulo': typeof AdminKpisModuloRoute
  '/admin/lancamentos/$id': typeof AdminLancamentosIdRoute
  '/api/evidencias/admin-submit': typeof ApiEvidenciasAdminSubmitRoute
  '/api/evidencias/batch-submit': typeof ApiEvidenciasBatchSubmitRoute
  '/api/evidencias/notify-email': typeof ApiEvidenciasNotifyEmailRoute
  '/api/evidencias/submit': typeof ApiEvidenciasSubmitRoute
  '/api/evidencias/test-email': typeof ApiEvidenciasTestEmailRoute
  '/admin/kpis/': typeof AdminKpisIndexRoute
  '/admin/lancamentos/': typeof AdminLancamentosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/alterar'
    | '/cadastro'
    | '/estoque-atlas'
    | '/estoque-base'
    | '/estoque-fisico-btp'
    | '/estoque-tecnico'
    | '/historico'
    | '/login'
    | '/media-baixa-tecnico'
    | '/metragem'
    | '/previsao-reserva'
    | '/relatorio'
    | '/tecnicos'
    | '/todos'
    | '/admin/enviar-evidencia'
    | '/admin/importacao'
    | '/admin/pendencias'
    | '/admin/'
    | '/admin/kpis/$modulo'
    | '/admin/lancamentos/$id'
    | '/api/evidencias/admin-submit'
    | '/api/evidencias/batch-submit'
    | '/api/evidencias/notify-email'
    | '/api/evidencias/submit'
    | '/api/evidencias/test-email'
    | '/admin/kpis/'
    | '/admin/lancamentos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alterar'
    | '/cadastro'
    | '/estoque-atlas'
    | '/estoque-base'
    | '/estoque-fisico-btp'
    | '/estoque-tecnico'
    | '/historico'
    | '/login'
    | '/media-baixa-tecnico'
    | '/metragem'
    | '/previsao-reserva'
    | '/relatorio'
    | '/tecnicos'
    | '/todos'
    | '/admin/enviar-evidencia'
    | '/admin/importacao'
    | '/admin/pendencias'
    | '/admin'
    | '/admin/kpis/$modulo'
    | '/admin/lancamentos/$id'
    | '/api/evidencias/admin-submit'
    | '/api/evidencias/batch-submit'
    | '/api/evidencias/notify-email'
    | '/api/evidencias/submit'
    | '/api/evidencias/test-email'
    | '/admin/kpis'
    | '/admin/lancamentos'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/alterar'
    | '/cadastro'
    | '/estoque-atlas'
    | '/estoque-base'
    | '/estoque-fisico-btp'
    | '/estoque-tecnico'
    | '/historico'
    | '/login'
    | '/media-baixa-tecnico'
    | '/metragem'
    | '/previsao-reserva'
    | '/relatorio'
    | '/tecnicos'
    | '/todos'
    | '/admin/enviar-evidencia'
    | '/admin/importacao'
    | '/admin/pendencias'
    | '/admin/'
    | '/admin/kpis/$modulo'
    | '/admin/lancamentos/$id'
    | '/api/evidencias/admin-submit'
    | '/api/evidencias/batch-submit'
    | '/api/evidencias/notify-email'
    | '/api/evidencias/submit'
    | '/api/evidencias/test-email'
    | '/admin/kpis/'
    | '/admin/lancamentos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AlterarRoute: typeof AlterarRoute
  CadastroRoute: typeof CadastroRoute
  EstoqueAtlasRoute: typeof EstoqueAtlasRoute
  EstoqueBaseRoute: typeof EstoqueBaseRoute
  EstoqueFisicoBtpRoute: typeof EstoqueFisicoBtpRoute
  EstoqueTecnicoRoute: typeof EstoqueTecnicoRoute
  HistoricoRoute: typeof HistoricoRoute
  LoginRoute: typeof LoginRoute
  MediaBaixaTecnicoRoute: typeof MediaBaixaTecnicoRoute
  MetragemRoute: typeof MetragemRoute
  PrevisaoReservaRoute: typeof PrevisaoReservaRoute
  RelatorioRoute: typeof RelatorioRoute
  TecnicosRoute: typeof TecnicosRoute
  TodosRoute: typeof TodosRoute
  ApiEvidenciasAdminSubmitRoute: typeof ApiEvidenciasAdminSubmitRoute
  ApiEvidenciasBatchSubmitRoute: typeof ApiEvidenciasBatchSubmitRoute
  ApiEvidenciasNotifyEmailRoute: typeof ApiEvidenciasNotifyEmailRoute
  ApiEvidenciasSubmitRoute: typeof ApiEvidenciasSubmitRoute
  ApiEvidenciasTestEmailRoute: typeof ApiEvidenciasTestEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/todos': {
      id: '/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof TodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tecnicos': {
      id: '/tecnicos'
      path: '/tecnicos'
      fullPath: '/tecnicos'
      preLoaderRoute: typeof TecnicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorio': {
      id: '/relatorio'
      path: '/relatorio'
      fullPath: '/relatorio'
      preLoaderRoute: typeof RelatorioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/previsao-reserva': {
      id: '/previsao-reserva'
      path: '/previsao-reserva'
      fullPath: '/previsao-reserva'
      preLoaderRoute: typeof PrevisaoReservaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metragem': {
      id: '/metragem'
      path: '/metragem'
      fullPath: '/metragem'
      preLoaderRoute: typeof MetragemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media-baixa-tecnico': {
      id: '/media-baixa-tecnico'
      path: '/media-baixa-tecnico'
      fullPath: '/media-baixa-tecnico'
      preLoaderRoute: typeof MediaBaixaTecnicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque-tecnico': {
      id: '/estoque-tecnico'
      path: '/estoque-tecnico'
      fullPath: '/estoque-tecnico'
      preLoaderRoute: typeof EstoqueTecnicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque-fisico-btp': {
      id: '/estoque-fisico-btp'
      path: '/estoque-fisico-btp'
      fullPath: '/estoque-fisico-btp'
      preLoaderRoute: typeof EstoqueFisicoBtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque-base': {
      id: '/estoque-base'
      path: '/estoque-base'
      fullPath: '/estoque-base'
      preLoaderRoute: typeof EstoqueBaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque-atlas': {
      id: '/estoque-atlas'
      path: '/estoque-atlas'
      fullPath: '/estoque-atlas'
      preLoaderRoute: typeof EstoqueAtlasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alterar': {
      id: '/alterar'
      path: '/alterar'
      fullPath: '/alterar'
      preLoaderRoute: typeof AlterarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pendencias': {
      id: '/admin/pendencias'
      path: '/pendencias'
      fullPath: '/admin/pendencias'
      preLoaderRoute: typeof AdminPendenciasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/importacao': {
      id: '/admin/importacao'
      path: '/importacao'
      fullPath: '/admin/importacao'
      preLoaderRoute: typeof AdminImportacaoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/enviar-evidencia': {
      id: '/admin/enviar-evidencia'
      path: '/enviar-evidencia'
      fullPath: '/admin/enviar-evidencia'
      preLoaderRoute: typeof AdminEnviarEvidenciaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lancamentos/': {
      id: '/admin/lancamentos/'
      path: '/lancamentos'
      fullPath: '/admin/lancamentos/'
      preLoaderRoute: typeof AdminLancamentosIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kpis/': {
      id: '/admin/kpis/'
      path: '/kpis'
      fullPath: '/admin/kpis/'
      preLoaderRoute: typeof AdminKpisIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/evidencias/test-email': {
      id: '/api/evidencias/test-email'
      path: '/api/evidencias/test-email'
      fullPath: '/api/evidencias/test-email'
      preLoaderRoute: typeof ApiEvidenciasTestEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/evidencias/submit': {
      id: '/api/evidencias/submit'
      path: '/api/evidencias/submit'
      fullPath: '/api/evidencias/submit'
      preLoaderRoute: typeof ApiEvidenciasSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/evidencias/notify-email': {
      id: '/api/evidencias/notify-email'
      path: '/api/evidencias/notify-email'
      fullPath: '/api/evidencias/notify-email'
      preLoaderRoute: typeof ApiEvidenciasNotifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/evidencias/batch-submit': {
      id: '/api/evidencias/batch-submit'
      path: '/api/evidencias/batch-submit'
      fullPath: '/api/evidencias/batch-submit'
      preLoaderRoute: typeof ApiEvidenciasBatchSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/evidencias/admin-submit': {
      id: '/api/evidencias/admin-submit'
      path: '/api/evidencias/admin-submit'
      fullPath: '/api/evidencias/admin-submit'
      preLoaderRoute: typeof ApiEvidenciasAdminSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/lancamentos/$id': {
      id: '/admin/lancamentos/$id'
      path: '/lancamentos/$id'
      fullPath: '/admin/lancamentos/$id'
      preLoaderRoute: typeof AdminLancamentosIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kpis/$modulo': {
      id: '/admin/kpis/$modulo'
      path: '/kpis/$modulo'
      fullPath: '/admin/kpis/$modulo'
      preLoaderRoute: typeof AdminKpisModuloRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminEnviarEvidenciaRoute: typeof AdminEnviarEvidenciaRoute
  AdminImportacaoRoute: typeof AdminImportacaoRoute
  AdminPendenciasRoute: typeof AdminPendenciasRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminKpisModuloRoute: typeof AdminKpisModuloRoute
  AdminLancamentosIdRoute: typeof AdminLancamentosIdRoute
  AdminKpisIndexRoute: typeof AdminKpisIndexRoute
  AdminLancamentosIndexRoute: typeof AdminLancamentosIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminEnviarEvidenciaRoute: AdminEnviarEvidenciaRoute,
  AdminImportacaoRoute: AdminImportacaoRoute,
  AdminPendenciasRoute: AdminPendenciasRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminKpisModuloRoute: AdminKpisModuloRoute,
  AdminLancamentosIdRoute: AdminLancamentosIdRoute,
  AdminKpisIndexRoute: AdminKpisIndexRoute,
  AdminLancamentosIndexRoute: AdminLancamentosIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AlterarRoute: AlterarRoute,
  CadastroRoute: CadastroRoute,
  EstoqueAtlasRoute: EstoqueAtlasRoute,
  EstoqueBaseRoute: EstoqueBaseRoute,
  EstoqueFisicoBtpRoute: EstoqueFisicoBtpRoute,
  EstoqueTecnicoRoute: EstoqueTecnicoRoute,
  HistoricoRoute: HistoricoRoute,
  LoginRoute: LoginRoute,
  MediaBaixaTecnicoRoute: MediaBaixaTecnicoRoute,
  MetragemRoute: MetragemRoute,
  PrevisaoReservaRoute: PrevisaoReservaRoute,
  RelatorioRoute: RelatorioRoute,
  TecnicosRoute: TecnicosRoute,
  TodosRoute: TodosRoute,
  ApiEvidenciasAdminSubmitRoute: ApiEvidenciasAdminSubmitRoute,
  ApiEvidenciasBatchSubmitRoute: ApiEvidenciasBatchSubmitRoute,
  ApiEvidenciasNotifyEmailRoute: ApiEvidenciasNotifyEmailRoute,
  ApiEvidenciasSubmitRoute: ApiEvidenciasSubmitRoute,
  ApiEvidenciasTestEmailRoute: ApiEvidenciasTestEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
