-- Dicionário Cód. Baixa → descrição do motivo (TOA / Quebras).
CREATE TABLE IF NOT EXISTS public.dicionario_codigos_baixa (
  codigo VARCHAR(10) PRIMARY KEY,
  descricao VARCHAR(255) NOT NULL
);

ALTER TABLE public.dicionario_codigos_baixa ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "dicionario_codigos_baixa_admin_all" ON public.dicionario_codigos_baixa;
CREATE POLICY "dicionario_codigos_baixa_admin_all"
  ON public.dicionario_codigos_baixa FOR ALL
  USING (public.is_admin())
  WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS "dicionario_codigos_baixa_authenticated_select" ON public.dicionario_codigos_baixa;
CREATE POLICY "dicionario_codigos_baixa_authenticated_select"
  ON public.dicionario_codigos_baixa FOR SELECT
  TO authenticated
  USING (true);

INSERT INTO public.dicionario_codigos_baixa (codigo, descricao) VALUES
('101', 'ENDERECO NAO LOCALIZADO'),
('104', 'FALTA DE MATERIAL'),
('106', 'CLIENTE AUSENTE'),
('107', 'ENTRADA NAO AUTORIZADA'),
('110', 'PROBLEMA NA TUBULACAO'),
('112', 'SEM ACESSO AO DG / SOTAO / COMODO'),
('125', 'CLIENTE DESISTE DA AGENDA'),
('126', 'SITUACAO PONTUAL DE RISCO'),
('127', 'AREA DE RISCO BLOQUEIO DE ENDERECO'),
('128', 'TUB. GPON OBSTRUIDA SOLUCAO COM CABO HFC'),
('134', 'ADEQUACAO MDU INICIADA MAS NAO CONCLUIDA'),
('203', 'REDE EXTERNA COM PROBLEMA'),
('204', 'BACKBONE COM PROBLEMA'),
('206', 'PREDIO SEM BACKBONE'),
('209', 'NAP LOTADA EM MDU'),
('211', 'FALTA NAP/NAP LOTADA'),
('217', 'BACKBONE GPON COM PROBLEMA'),
('301', 'TIPO DE OS INCORRETA'),
('302', 'DESISTENCIA DA ASSINATURA / SERVICO'),
('303', 'INST MODELO CABO CASA NAO ACEITA PELO CLIENTE'),
('305', 'RUA NAO CABEADA'),
('306', 'NAO RESIDE NO ENDERECO'),
('308', 'INSTALACAO NAO CONTEMPLARA PADRAO'),
('312', 'CLIENTE NAO SOLICITOU O SERVICO'),
('316', 'RUA NAO CABEADA GPON'),
('328', 'ENTREGA CONCLUIDA'),
('402', 'DIVERGENCIA DE DADOS CADASTRAIS'),
('409', 'SERVICO CONCLUIDO'),
('410', 'AUTO INSTALAÇÃO CONCLUÍDA'),
('425', 'TROCA DE TECNOLOGIA'),
('430', 'EQUIPAMENTO RETIRADO'),
('467', 'RESOLVIDO DURANTE A VISTORIA'),
('469', 'CASO INDEFINIDO'),
('476', 'RECONFIGURADO - PAREAMENTO EXTENSORES'),
('477', 'INSTALACAO MESH CABEADA'),
('478', 'CONFIGURACAO CONCLUIDA'),
('480', 'DIVERGENCIA POLITICA PRODUTO MESH'),
('484', 'TROCA DE EXTENSOR MESH QUEIMADO'),
('505', 'PASSIVO INTERNO QUEIM./DEGRAD. - TROCA'),
('510', 'FONTE COM DEFEITO - TROCA'),
('514', 'ENVIO DE HIT - HABILITAR CANAIS'),
('516', 'T.T - TRAVADO'),
('517', 'T.T - QUEIMADO'),
('521', 'T.T - INTERMITENTE'),
('523', 'T.T - ALCANCE WIFI'),
('527', 'T.T - NAO NAVEGA'),
('529', 'T.T - MODELO NAO COMPATIVEL'),
('533', 'RESET NA CONFIG TERMINAL - TRAVADO'),
('536', 'RECONFIGURADO ROTEADOR DO CLIENTE'),
('537', 'RECONFIGURADO EMTA/ROTEADOR NET-WIFI'),
('539', 'RECONFIGURACAO DE AUDIO'),
('546', 'CONECTOR MDU  OXIDADO - TROCA'),
('555', 'SEM DEFEITO NO PRODUTO VIRTUA RECLAMADO'),
('557', 'SEM DEFEITO NO PRODUTO NETFONE RECLAMADO'),
('559', 'RECONFIGURADO COMPUTADOR'),
('560', 'EQUIPAMENTO / REDE DE DADOS CLIENTE COM DEFEITO'),
('562', 'CABO RECONECTADO/IDENTIFICADO'),
('564', 'CABOS ESPECIAIS COM DEFEITO - TROCA'),
('575', 'TOMADA TELEFONE COM PROBLEMA - TROCA'),
('582', 'ROTEADOR COM PROBLEMA'),
('584', 'CONECTOR OPTICO INTERNO DANIFICADO'),
('598', 'SERVICO CONCLUIDO PARA CONSTRUCAO DE MDU'),
('605', 'CANCELADO POR ATIVO / TIPO DE OS INCORRETA')
ON CONFLICT (codigo) DO UPDATE SET descricao = EXCLUDED.descricao;
